# Generated by Django 5.2.1 on 2025-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='license_plate',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=2, max_length=30, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Chat ID'),
        ),
    ]
